language: elixir

elixir:
  - 1.9

otp_release:
  - 22.0

script:
  - mix do local.hex --force
  - mix deps.get
  - mix format --check-formatted
  - mix test
  - travis_wait mix dialyzer --halt-exit-status

cache:
  directories:
    - priv/plts

